//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Grocery_Order.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_email { get; set; }
        public string u_address { get; set; }
        public string u_contact { get; set; }
        public string u_type { get; set; }
        public byte[] u_img { get; set; }
        public string u_img_type { get; set; }
        public string u_gender { get; set; }
        public string u_password { get; set; }
    }
}
