//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Grocery_Order
{
    using System;
    using System.Collections.Generic;
    
    public partial class attach
    {
        public int AttachID { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<int> AttachProduct { get; set; }
    
        public virtual product product { get; set; }
    }
}
