//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Grocery_Order
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int cart_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
