//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Grocery_Order
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int v_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> p_qty { get; set; }
        public Nullable<int> o_id { get; set; }
        public Nullable<int> p_price { get; set; }
        public string p_return { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
