//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Grocery_Order
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.invoices = new HashSet<invoice>();
            this.repeats = new HashSet<repeat>();
        }
    
        public int o_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public string shipping { get; set; }
        public string repeat { get; set; }
        public Nullable<int> period { get; set; }
        public string status { get; set; }
        public Nullable<int> boy_id { get; set; }
        public Nullable<System.DateTime> p_date { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public Nullable<System.DateTime> d_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repeat> repeats { get; set; }
    }
}
