//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Grocery_Order
{
    using System;
    using System.Collections.Generic;
    
    public partial class repeat
    {
        public int r_id { get; set; }
        public Nullable<int> o_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public string status { get; set; }
        public string shipping { get; set; }
        public Nullable<System.DateTime> p_date { get; set; }
        public Nullable<System.DateTime> d_date { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public Nullable<int> boy_id { get; set; }
    
        public virtual order order { get; set; }
        public virtual user user { get; set; }
    }
}
