//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Grocery_Order
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.carts = new HashSet<cart>();
            this.orders = new HashSet<order>();
            this.orders1 = new HashSet<order>();
            this.repeats = new HashSet<repeat>();
        }
    
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_address { get; set; }
        public string u_contact { get; set; }
        public string u_type { get; set; }
        public byte[] u_img { get; set; }
        public string u_img_type { get; set; }
        public string u_gender { get; set; }
        public string u_password { get; set; }
        public string u_email { get; set; }
        public Nullable<System.DateTime> i_date { get; set; }
        public string u_address_office { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repeat> repeats { get; set; }
    }
}
